name: Firewall Rule Automation

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Validate Firewall Rules
        run: python validate_firewall_changes.py security_rules.json

  apply:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_palo_alto_hostname: ${{ secrets.PALO_ALTO_HOSTNAME }}
          TF_VAR_palo_alto_username: ${{ secrets.PALO_ALTO_USERNAME }}
          TF_VAR_palo_alto_password: ${{ secrets.PALO_ALTO_PASSWORD }}

