name: Firewall Rule Automation

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Terraform (for validation)
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.9.0'

      - name: Validate Firewall Rules
        run: python validate_firewall_changes.py security_rules.json

  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.9.0'

      - name: Terraform Init
        run: terraform init
     
      - name: Terraform Apply
        run: terraform apply -auto-approve
        
